default:
  tags:
    - ci

stages:
  - build

maven-build:
  image: maven:latest
  stage: build
  script: "mvn compile package -B -X"
  artifacts:
    paths:
      - target/vcharugin-0.0.1-SNAPSHOT.jar